# This is an example GitHub Actions workflow that will allow you to build your project with every push or pull request.
# For more information, see:
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: Rust Code Quality

on:
  workflow_dispatch:

jobs:
  rust_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Cargo FMT
      run: cargo fmt --check
  test_n_build:
    needs: rust_lint
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Test Rust code
      run: cargo test
    - name: Make sure Rust builds correctly
      run: cargo build
